name: checkout

on:
  schedule:
    - cron: "0 0/6 * * *"
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python xxxxx520.py